Fheos
FhenixProtocol/fhevm pull request #1
Opened 2023-10-26 15:52 UTC by liorbond

2023-10-30 17:54 UTC, Cashmaney commented on lib/Impl.sol
> +    function mul(uint256 lhs, uint256 rhs, bool scalar) internal view returns (uint256 result) {
Can you add some docs on the logic here? There's some magic here that we should document for future us

2023-10-30 17:54 UTC, Cashmaney commented on lib/Impl.sol
> +            actualData[i] = data[i + 32];
This seems really inefficient for gas usage. Is there a better way to do this?

2023-10-30 17:54 UTC, Cashmaney commented on lib/Impl.sol
> +    function skipFirst32Bytes(bytes memory data) public pure returns (bytes memory) {
Just making sure we intend this function to be public? Also, this (and other functions) need a bit of documentation

2023-10-30 17:54 UTC, Cashmaney commented on lib/Impl.sol
> +        uint32 inputLen = uint32(input.length);
Seems like there's a bunch of code being repeated. Can we add a helper function instead of copy-pasting?

2023-10-30 17:54 UTC, Cashmaney commented on lib/Impl.sol
>      // 32 bytes for the 'byte' header + 16553 bytes of key data.
Commenting here, but it's not in the diff: After changes, reencryptedSize is unused

2023-11-06 15:49 UTC, liorbond commented on lib/Impl.sol
> +    function skipFirst32Bytes(bytes memory data) public pure returns (bytes memory) {
nope, fixed

2023-11-06 15:50 UTC, liorbond commented on lib/Impl.sol
> +            actualData[i] = data[i + 32];
Removed the function not using it anymore - better gas :smile:

2023-11-06 15:55 UTC, liorbond commented on lib/Impl.sol
> +    function mul(uint256 lhs, uint256 rhs, bool scalar) internal view returns (uint256 result) {
done

2023-11-07 05:43 UTC, Cashmaney approved these changes

2023-11-07 05:43 UTC, Cashmaney commented
Conflicts etc.

2023-11-08 11:03 UTC, toml01 requested changes

2023-11-08 15:27 UTC, liorbond commented on lib/Impl.sol
> +            value := mload(add(a, 0x20))
Not sure, copied from zama and it works (Although there is no toEVMBytes() in the code)

2023-11-09 10:41 UTC, toml01 commented on lib/Impl.sol
> +            value := mload(add(a, 0x20))
Interesting, oh well

2023-11-09 10:42 UTC, toml01 approved these changes

2023-11-09 14:04 UTC, merged